Fetch data and update Redux store
lily4178993/space-traveller pull request #30
Opened 2023-10-03 08:53 UTC by mryeminthu

Upon first render fetch data from the SpaceX API endpoints:
Rockets: https://api.spacexdata.com/v4/rockets

2023-10-03 09:50 UTC, lily4178993 commented on src/components/Rockets.jsx
> +  }, []);
To meet the requirement, you should modify the **`Rockets`** component to dispatch an action to store the fetched data in the Redux store. Here is an example:

```js
// ...rest of your code...
useEffect(() => {
    fetch('https://api.spacexdata.com/v3/rockets')
      .then((response) => response.json())
      .then((data) => {
        // Dispatch an action to store the fetched data in Redux
        dispatch(fetchRockets(data));
        setRocketData(data);
      })
      .catch(() => {});
  }, [dispatch]);
```
// ...rest of your code...

2023-10-03 09:51 UTC, lily4178993 commented on src/redux/rocketActions.js
> +});
Following the same logic, you have to create an action creator **`fetchRockets`** in your **rocketActions.js** file to handle storing the fetched data in the Redux store. Here is an example:

```js
// Action type to store fetched rockets
export const FETCH_ROCKETS = 'FETCH_ROCKETS';

// Action creator to store fetched rockets in Redux
export const fetchRockets = (rockets) => ({
  type: FETCH_ROCKETS,
  payload: rockets,
});

// ... Rest of your code ...
```

2023-10-03 09:51 UTC, lily4178993 commented on src/redux/rocketReducer.js
> +
Update your **rocketReducer.js** to handle the **FETCH_ROCKETS** action and store the rocket data in the Redux store. Here is an example: 
```js
// Import the action type
import { FETCH_ROCKETS } from './rocketActions';

const initialState = {
  rockets: [],
};

const rocketReducer = (state = initialState, action) => {
  switch (action.type) {
    case FETCH_ROCKETS:
      return { ...state, rockets: action.payload };

    // ... Other reducer cases ...
  }
};

export default rocketReducer;

```

2023-10-03 09:51 UTC, lily4178993 requested changes
Hi @mryeminthu

I've reviewed the code you shared for the Rockets components. Overall, it's looking good, but there are a couple of points to consider for improvement:

1. **Data Fetching for Rockets:**
The code currently fetches data from the endpoint `https://api.spacexdata.com/v4/rockets`, while the requirement specifies fetching data from `https://api.spacexdata.com/v3/rockets`. Please update the fetch URL to target the correct endpoint.

2. **Storing Fetched Data:**
It appears that the code does not store the fetched data from the Rockets endpoint in the Redux store. To meet the requirement, you should dispatch an action to store the selected data in Redux, including fields such as id, name, type, and flickr_images.

3. **Redux Actions and Reducer:**
Ensure that you have the necessary Redux action creators and reducers to handle the data fetching and storage process correctly. The **`rocketActions.js`** and **`rocketReducer.js`** files need to be updated.

Once these adjustments are made, the code should align with the specified requirements for data fetching and storage in the Redux store.

Feel free to reach out if you have any questions or need further assistance with the changes. Keep up the good work!

2023-10-04 07:26 UTC, lily4178993 requested changes
Hi @mryeminthu, please make sure to correctly configure the store by importing the **rocketsReducer** from the **rocketsSlice.js** file in the **store**. 

The yellow boxes is what you have to add in order to configure your store:
![Capture d’écran (390)](https://github.com/lily4178993/space-traveller/assets/101261047/d6af7ebf-fe84-46bb-bd7c-b87aacc2541f)

- Before the configuration of the store:

![Capture d’écran (391)](https://github.com/lily4178993/space-traveller/assets/101261047/ea06223e-aa3a-4c27-b692-3ab64f332876)

- Screenshot after correclty configured the store

![Capture d’écran (389)](https://github.com/lily4178993/space-traveller/assets/101261047/be588f8c-eadf-4e8c-95fb-a057f30bff4b)


Thanks!

2023-10-04 07:30 UTC, mryeminthu commented
Hello please just check my last pull request. What you mention is included in it.

2023-10-04 08:12 UTC, closed without merging